name: pixel_border
description: A flutter package providing a ShapeBorder to give the shape or border of widgets a pixel-y look.
version: 2.0.0-nullsafety.0
homepage: https://github.com/aqulu/flutter_pixel_border

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
